[tool.black]
line-length = 100

[tool.codespell]
skip = "examples/comparison_neurodesign.html,examples/comparison_neurodesign.ipynb"

[tool.isort]
combine_as_imports = true
line_length = 100
profile = "black"
skip_gitignore = true
